package com.example.zwy.greendaodemo.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.zwy.greendaodemo.entity.Books;

import com.example.zwy.greendaodemo.entity.BooksDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig booksDaoConfig;

    private final BooksDao booksDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        booksDaoConfig = daoConfigMap.get(BooksDao.class).clone();
        booksDaoConfig.initIdentityScope(type);

        booksDao = new BooksDao(booksDaoConfig, this);

        registerDao(Books.class, booksDao);
    }
    
    public void clear() {
        booksDaoConfig.clearIdentityScope();
    }

    public BooksDao getBooksDao() {
        return booksDao;
    }

}
